# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: qcksys.qlipq
PackageVersion: 0.1.2
InstallerType: inno
Scope: machine
UpgradeBehavior: install
ProductCode: '{36C074CA-3CDE-4FD8-A823-778FF2B56CCB}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/qcksys/qlipq/releases/download/v0.1.2/qlipq-setup-x64.exe
  InstallerSha256: 1C1FC6AC5020CD20E20E79357F28079F25D04CB3C499D299BAEC1B6FD9C593B5
ManifestType: installer
ManifestVersion: 1.6.0
